//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDungCu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADV
    {
        public int ID { get; set; }
        public string TENADV { get; set; }
        public string MOTA { get; set; }
        public string IMG { get; set; }
        public Nullable<int> LOAI { get; set; }
        public string LINK { get; set; }
    }
}
