//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDungCu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int ID { get; set; }
        public string TEN { get; set; }
        public string WEBSITE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ISREAD { get; set; }
        public string MESSAGE { get; set; }
    }
}
