//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDungCu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
        }
    
        public int ID { get; set; }
        public string TENSP { get; set; }
        public string MOTA { get; set; }
        public string IMG { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public Nullable<int> MATH { get; set; }
        public bool IsHome { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
